services:
    redis_bundle:
        container_name: redis-bundle
        hostname: redis-bundle
        build:
            context: ./
            dockerfile: ./containers/redis-bundle/Dockerfile
        image: lehuygiang28/vkara-api-redis:${COMPOSE_TAG:-latest}
        env_file:
            - ./containers/redis-bundle/.env
        ports:
            - 8000:${PORT:-8000}
        networks:
            - vkara_net
        restart: unless-stopped

networks:
    vkara_net:
